// Slice web-features down to what the rules actually ask for.
//
// The full package is 4.5MB of data for 1,189 features; the rules read a support
// table for a couple of dozen. Generated from the rules themselves so adding a
// rule cannot silently leave the slice behind.
import { writeFileSync } from 'node:fs'
import { features } from 'web-features'
import { rules } from '../dist/rules/index.js'

const requirements = new Set()
for (const rule of rules) {
  for (const requirement of rule.requirements ?? []) requirements.add(requirement)
  if (!rule.requirementsFor) continue
  for (const pkg of rule.packages) {
    for (const requirement of rule.requirementsFor(pkg)) requirements.add(requirement)
  }
}

function realFeature(id, depth = 0) {
  const entry = features[id]
  if (entry && 'status' in entry) return entry
  if (!entry || depth > 3) return null
  if (entry.kind === 'moved' && entry.redirect_target) return realFeature(entry.redirect_target, depth + 1)
  return null
}

const picked = {}
const keys = {}
const missing = []

for (const requirement of [...requirements].sort()) {
  const [kind, id] = [requirement.slice(0, requirement.indexOf(':')), requirement.slice(requirement.indexOf(':') + 1)]

  if (kind === 'feature') {
    const feature = realFeature(id)
    if (!feature) { missing.push(requirement); continue }
    picked[id] = { name: feature.name ?? id, support: feature.status.support ?? {} }
    continue
  }

  let found = false
  for (const feature of Object.values(features)) {
    if (!('status' in feature)) continue
    const entry = feature.status.by_compat_key?.[id]
    if (!entry) continue
    keys[id] = { support: entry.support ?? {} }
    found = true
    break
  }
  if (!found) missing.push(requirement)
}

if (missing.length) {
  console.error(`build-data: no support data for ${missing.join(', ')}`)
  process.exit(1)
}

const today = new Date().toISOString().slice(0, 10)
const file = `// Generated by \`npm run build:data\` — do not edit.
// Source: web-features. Sliced to the requirements declared by src/rules.

export const GENERATED_AT = '${today}'

export const FEATURES: Record<string, { name: string; support: Record<string, string> }> = ${JSON.stringify(picked, null, 2)}

export const COMPAT_KEYS: Record<string, { support: Record<string, string> }> = ${JSON.stringify(keys, null, 2)}
`

writeFileSync(new URL('../src/data/baseline.generated.ts', import.meta.url), file)
console.log(`build-data: ${Object.keys(picked).length} features, ${Object.keys(keys).length} compat keys, ${(file.length / 1024).toFixed(1)}KB`)
