// Generated by `npm run build:data` — do not edit.
// Source: web-features. Sliced to the requirements declared by src/rules.

export const GENERATED_AT = '2026-08-27'

export const FEATURES: Record<string, { name: string; support: Record<string, string> }> = {
  "aborting": {
    "name": "AbortController and AbortSignal",
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "16",
      "firefox": "57",
      "firefox_android": "57",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "abortsignal-timeout": {
    "name": "AbortSignal.timeout()",
    "support": {
      "chrome": "124",
      "chrome_android": "124",
      "edge": "124",
      "firefox": "100",
      "firefox_android": "100",
      "safari": "16",
      "safari_ios": "16"
    }
  },
  "array-flat": {
    "name": "Array flat() and flatMap()",
    "support": {
      "chrome": "69",
      "chrome_android": "69",
      "edge": "79",
      "firefox": "62",
      "firefox_android": "62",
      "safari": "12",
      "safari_ios": "12"
    }
  },
  "aspect-ratio": {
    "name": "aspect-ratio",
    "support": {
      "chrome": "88",
      "chrome_android": "88",
      "edge": "88",
      "firefox": "89",
      "firefox_android": "89",
      "safari": "15",
      "safari_ios": "15"
    }
  },
  "async-clipboard": {
    "name": "Async clipboard",
    "support": {
      "chrome": "76",
      "chrome_android": "76",
      "edge": "79",
      "firefox": "127",
      "firefox_android": "127",
      "safari": "13.1",
      "safari_ios": "13.4"
    }
  },
  "broadcast-channel": {
    "name": "BroadcastChannel",
    "support": {
      "chrome": "54",
      "chrome_android": "54",
      "edge": "79",
      "firefox": "38",
      "firefox_android": "38",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "canvas-roundrect": {
    "name": "Canvas roundRect()",
    "support": {
      "chrome": "99",
      "chrome_android": "99",
      "edge": "99",
      "firefox": "112",
      "firefox_android": "112",
      "safari": "16.4",
      "safari_ios": "16.4"
    }
  },
  "compression-streams": {
    "name": "Compression streams",
    "support": {
      "chrome": "80",
      "chrome_android": "80",
      "edge": "80",
      "firefox": "113",
      "firefox_android": "113",
      "safari": "16.4",
      "safari_ios": "16.4"
    }
  },
  "constructed-stylesheets": {
    "name": "Constructed stylesheets",
    "support": {
      "chrome": "73",
      "chrome_android": "73",
      "edge": "79",
      "firefox": "101",
      "firefox_android": "101",
      "safari": "16.4",
      "safari_ios": "16.4"
    }
  },
  "container-queries": {
    "name": "Container queries",
    "support": {
      "chrome": "105",
      "chrome_android": "105",
      "edge": "105",
      "firefox": "110",
      "firefox_android": "110",
      "safari": "16",
      "safari_ios": "16"
    }
  },
  "dialog": {
    "name": "<dialog>",
    "support": {
      "chrome": "37",
      "chrome_android": "37",
      "edge": "79",
      "firefox": "98",
      "firefox_android": "98",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "events": {
    "name": "Events",
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "fetch": {
    "name": "Fetch",
    "support": {
      "chrome": "42",
      "chrome_android": "42",
      "edge": "14",
      "firefox": "39",
      "firefox_android": "39",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "focus-visible": {
    "name": ":focus-visible",
    "support": {
      "chrome": "86",
      "chrome_android": "86",
      "edge": "86",
      "firefox": "85",
      "firefox_android": "85",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "image-set": {
    "name": "image-set()",
    "support": {
      "chrome": "113",
      "chrome_android": "113",
      "edge": "113",
      "firefox": "89",
      "firefox_android": "89",
      "safari": "17",
      "safari_ios": "17"
    }
  },
  "inert": {
    "name": "inert",
    "support": {
      "chrome": "102",
      "chrome_android": "102",
      "edge": "102",
      "firefox": "112",
      "firefox_android": "112",
      "safari": "15.5",
      "safari_ios": "15.5"
    }
  },
  "intersection-observer": {
    "name": "Intersection observer",
    "support": {
      "chrome": "58",
      "chrome_android": "58",
      "edge": "16",
      "firefox": "55",
      "firefox_android": "55",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "intl-locale-info": {
    "name": "Intl.Locale info",
    "support": {
      "chrome": "130",
      "chrome_android": "130",
      "edge": "130",
      "firefox": "153",
      "firefox_android": "153",
      "safari": "17",
      "safari_ios": "17"
    }
  },
  "intl-segmenter": {
    "name": "Intl.Segmenter",
    "support": {
      "chrome": "87",
      "chrome_android": "87",
      "edge": "87",
      "firefox": "125",
      "firefox_android": "125",
      "safari": "14.1",
      "safari_ios": "14.5"
    }
  },
  "invoker-commands": {
    "name": "Invoker commands",
    "support": {
      "chrome": "135",
      "chrome_android": "135",
      "edge": "135",
      "firefox": "144",
      "firefox_android": "144",
      "safari": "26.2",
      "safari_ios": "26.2"
    }
  },
  "iterator-methods": {
    "name": "Iterator methods",
    "support": {
      "chrome": "122",
      "chrome_android": "122",
      "edge": "122",
      "firefox": "131",
      "firefox_android": "131",
      "safari": "18.4",
      "safari_ios": "18.4"
    }
  },
  "loading-lazy": {
    "name": "Lazy-loading images and iframes",
    "support": {
      "chrome": "77",
      "chrome_android": "77",
      "edge": "79",
      "firefox": "121",
      "firefox_android": "121",
      "safari": "16.4",
      "safari_ios": "16.4"
    }
  },
  "object-fit": {
    "name": "object-fit",
    "support": {
      "chrome": "32",
      "chrome_android": "32",
      "edge": "79",
      "firefox": "36",
      "firefox_android": "36",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "popover": {
    "name": "Popover",
    "support": {
      "chrome": "116",
      "chrome_android": "116",
      "edge": "116",
      "firefox": "125",
      "firefox_android": "125",
      "safari": "17",
      "safari_ios": "18.3"
    }
  },
  "promise": {
    "name": "Promise (initial support)",
    "support": {
      "chrome": "32",
      "chrome_android": "32",
      "edge": "12",
      "firefox": "29",
      "firefox_android": "29",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "promise-finally": {
    "name": "Promise finally()",
    "support": {
      "chrome": "63",
      "chrome_android": "63",
      "edge": "18",
      "firefox": "58",
      "firefox_android": "58",
      "safari": "11.1",
      "safari_ios": "11.3"
    }
  },
  "request-animation-frame": {
    "name": "requestAnimationFrame()",
    "support": {
      "chrome": "24",
      "chrome_android": "25",
      "edge": "12",
      "firefox": "23",
      "firefox_android": "23",
      "safari": "7",
      "safari_ios": "7"
    }
  },
  "resize-observer": {
    "name": "Resize observer",
    "support": {
      "chrome": "64",
      "chrome_android": "64",
      "edge": "79",
      "firefox": "69",
      "firefox_android": "79",
      "safari": "13.1",
      "safari_ios": "13.4"
    }
  },
  "scroll-behavior": {
    "name": "scroll-behavior",
    "support": {
      "chrome": "61",
      "chrome_android": "61",
      "edge": "79",
      "firefox": "36",
      "firefox_android": "36",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "scroll-driven-animations": {
    "name": "Scroll-driven animations",
    "support": {
      "chrome": "115",
      "chrome_android": "115",
      "edge": "115",
      "safari": "26",
      "safari_ios": "26"
    }
  },
  "scroll-to-text-fragment": {
    "name": "Scroll to text fragment",
    "support": {
      "chrome": "80",
      "chrome_android": "80",
      "edge": "80",
      "firefox": "131",
      "firefox_android": "131",
      "safari": "16.1",
      "safari_ios": "16.1"
    }
  },
  "scrollend": {
    "name": "scrollend",
    "support": {
      "chrome": "114",
      "chrome_android": "114",
      "edge": "114",
      "firefox": "109",
      "firefox_android": "109",
      "safari": "26.2",
      "safari_ios": "26.2"
    }
  },
  "starting-style": {
    "name": "@starting-style",
    "support": {
      "chrome": "117",
      "chrome_android": "117",
      "edge": "117",
      "firefox": "129",
      "firefox_android": "129",
      "safari": "17.5",
      "safari_ios": "17.5"
    }
  },
  "streams": {
    "name": "Streams",
    "support": {
      "chrome": "67",
      "chrome_android": "67",
      "edge": "79",
      "firefox": "102",
      "firefox_android": "102",
      "safari": "14.1",
      "safari_ios": "14.5"
    }
  },
  "transition-behavior": {
    "name": "transition-behavior",
    "support": {
      "chrome": "117",
      "chrome_android": "117",
      "edge": "117",
      "firefox": "129",
      "firefox_android": "129",
      "safari": "17.4",
      "safari_ios": "17.4"
    }
  },
  "url": {
    "name": "URL",
    "support": {
      "chrome": "32",
      "chrome_android": "32",
      "edge": "12",
      "firefox": "19",
      "firefox_android": "19",
      "safari": "7",
      "safari_ios": "7"
    }
  },
  "urlpattern": {
    "name": "URLPattern",
    "support": {
      "chrome": "95",
      "chrome_android": "95",
      "edge": "95",
      "firefox": "142",
      "firefox_android": "142",
      "safari": "26",
      "safari_ios": "26"
    }
  },
  "viewport-unit-variants": {
    "name": "Small, large, and dynamic viewport units",
    "support": {
      "chrome": "108",
      "chrome_android": "108",
      "edge": "108",
      "firefox": "101",
      "firefox_android": "101",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  }
}

export const COMPAT_KEYS: Record<string, { support: Record<string, string> }> = {
  "api.AbortController.AbortController": {
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "16",
      "firefox": "57",
      "firefox_android": "57",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "api.Clipboard.writeText": {
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "79",
      "firefox": "63",
      "firefox_android": "63",
      "safari": "13.1",
      "safari_ios": "13.4"
    }
  },
  "api.Crypto.randomUUID": {
    "support": {
      "chrome": "92",
      "chrome_android": "92",
      "edge": "92",
      "firefox": "95",
      "firefox_android": "95",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "api.DOMException": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "api.EventTarget": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "api.SubtleCrypto": {
    "support": {
      "chrome": "37",
      "chrome_android": "37",
      "edge": "12",
      "firefox": "34",
      "firefox_android": "34",
      "safari": "11",
      "safari_ios": "11"
    }
  },
  "api.TextDecoder": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "79",
      "firefox": "19",
      "firefox_android": "19",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "api.TextEncoder.encode": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "79",
      "firefox": "18",
      "firefox_android": "18",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "api.URL": {
    "support": {
      "chrome": "32",
      "chrome_android": "32",
      "edge": "12",
      "firefox": "19",
      "firefox_android": "19",
      "safari": "7",
      "safari_ios": "7"
    }
  },
  "api.URL.canParse_static": {
    "support": {
      "chrome": "120",
      "chrome_android": "120",
      "edge": "120",
      "firefox": "115",
      "firefox_android": "115",
      "safari": "17",
      "safari_ios": "17"
    }
  },
  "api.atob": {
    "support": {
      "chrome": "4",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "api.btoa": {
    "support": {
      "chrome": "4",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "api.queueMicrotask": {
    "support": {
      "chrome": "71",
      "chrome_android": "71",
      "edge": "79",
      "firefox": "69",
      "firefox_android": "79",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "api.structuredClone": {
    "support": {
      "chrome": "98",
      "chrome_android": "98",
      "edge": "98",
      "firefox": "94",
      "firefox_android": "94",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "css.at-rules.position-try": {
    "support": {
      "chrome": "125",
      "chrome_android": "125",
      "edge": "125",
      "firefox": "147",
      "firefox_android": "147",
      "safari": "26",
      "safari_ios": "26"
    }
  },
  "css.properties.anchor-name": {
    "support": {
      "chrome": "125",
      "chrome_android": "125",
      "edge": "125",
      "firefox": "147",
      "firefox_android": "147",
      "safari": "26",
      "safari_ios": "26"
    }
  },
  "css.properties.field-sizing": {
    "support": {
      "chrome": "123",
      "chrome_android": "123",
      "edge": "123",
      "firefox": "152",
      "firefox_android": "152",
      "safari": "26.2",
      "safari_ios": "26.2"
    }
  },
  "css.properties.position-area": {
    "support": {
      "chrome": "129",
      "chrome_android": "129",
      "edge": "129",
      "firefox": "147",
      "firefox_android": "147",
      "safari": "26",
      "safari_ios": "26"
    }
  },
  "javascript.builtins.AggregateError": {
    "support": {
      "chrome": "85",
      "chrome_android": "85",
      "edge": "85",
      "firefox": "79",
      "firefox_android": "79",
      "safari": "14",
      "safari_ios": "14"
    }
  },
  "javascript.builtins.Array.@@unscopables": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "48",
      "firefox_android": "48",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.Array.at": {
    "support": {
      "chrome": "92",
      "chrome_android": "92",
      "edge": "92",
      "firefox": "90",
      "firefox_android": "90",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "javascript.builtins.Array.concat": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.copyWithin": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "32",
      "firefox_android": "32",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Array.entries": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "28",
      "firefox_android": "28",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Array.every": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.fill": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "31",
      "firefox_android": "31",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Array.filter": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.find": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "4",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Array.findIndex": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "4",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Array.findLast": {
    "support": {
      "chrome": "97",
      "chrome_android": "97",
      "edge": "97",
      "firefox": "104",
      "firefox_android": "104",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "javascript.builtins.Array.findLastIndex": {
    "support": {
      "chrome": "97",
      "chrome_android": "97",
      "edge": "97",
      "firefox": "104",
      "firefox_android": "104",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "javascript.builtins.Array.flat": {
    "support": {
      "chrome": "69",
      "chrome_android": "69",
      "edge": "79",
      "firefox": "62",
      "firefox_android": "62",
      "safari": "12",
      "safari_ios": "12"
    }
  },
  "javascript.builtins.Array.flatMap": {
    "support": {
      "chrome": "69",
      "chrome_android": "69",
      "edge": "79",
      "firefox": "62",
      "firefox_android": "62",
      "safari": "12",
      "safari_ios": "12"
    }
  },
  "javascript.builtins.Array.forEach": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.from": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "32",
      "firefox_android": "32",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Array.includes": {
    "support": {
      "chrome": "47",
      "chrome_android": "47",
      "edge": "14",
      "firefox": "43",
      "firefox_android": "43",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Array.indexOf": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.isArray": {
    "support": {
      "chrome": "4",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Array.join": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.keys": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "28",
      "firefox_android": "28",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Array.lastIndexOf": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.map": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.of": {
    "support": {
      "chrome": "45",
      "chrome_android": "39",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Array.push": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.reduce": {
    "support": {
      "chrome": "3",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "3",
      "firefox_android": "4",
      "safari": "4",
      "safari_ios": "3.2"
    }
  },
  "javascript.builtins.Array.reduceRight": {
    "support": {
      "chrome": "3",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "3",
      "firefox_android": "4",
      "safari": "4",
      "safari_ios": "3.2"
    }
  },
  "javascript.builtins.Array.slice": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.some": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1.5",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.splice": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.toReversed": {
    "support": {
      "chrome": "110",
      "chrome_android": "110",
      "edge": "110",
      "firefox": "115",
      "firefox_android": "115",
      "safari": "16",
      "safari_ios": "16"
    }
  },
  "javascript.builtins.Array.toSorted": {
    "support": {
      "chrome": "110",
      "chrome_android": "110",
      "edge": "110",
      "firefox": "115",
      "firefox_android": "115",
      "safari": "16",
      "safari_ios": "16"
    }
  },
  "javascript.builtins.Array.unshift": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Array.values": {
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "14",
      "firefox": "60",
      "firefox_android": "60",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.ArrayBuffer.byteLength": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.ArrayBuffer.slice": {
    "support": {
      "chrome": "17",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "12",
      "firefox_android": "14",
      "safari": "5.1",
      "safari_ios": "6"
    }
  },
  "javascript.builtins.AsyncIterator": {
    "support": {
      "chrome": "63",
      "chrome_android": "63",
      "edge": "79",
      "firefox": "57",
      "firefox_android": "57",
      "safari": "11.1",
      "safari_ios": "11.3"
    }
  },
  "javascript.builtins.BigInt": {
    "support": {
      "chrome": "67",
      "chrome_android": "67",
      "edge": "79",
      "firefox": "68",
      "firefox_android": "68",
      "safari": "14",
      "safari_ios": "14"
    }
  },
  "javascript.builtins.DataView": {
    "support": {
      "chrome": "9",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "15",
      "firefox_android": "15",
      "safari": "5.1",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.DataView.buffer": {
    "support": {
      "chrome": "9",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "15",
      "firefox_android": "15",
      "safari": "5.1",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.DataView.byteLength": {
    "support": {
      "chrome": "9",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "15",
      "firefox_android": "15",
      "safari": "5.1",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.DataView.byteOffset": {
    "support": {
      "chrome": "9",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "15",
      "firefox_android": "15",
      "safari": "5.1",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Date": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Date.now": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "4",
      "safari_ios": "4"
    }
  },
  "javascript.builtins.Error": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Error.cause": {
    "support": {
      "chrome": "93",
      "chrome_android": "93",
      "edge": "93",
      "firefox": "91",
      "firefox_android": "91",
      "safari": "15",
      "safari_ios": "15"
    }
  },
  "javascript.builtins.Error.isError": {
    "support": {
      "chrome": "134",
      "chrome_android": "134",
      "edge": "134",
      "firefox": "138",
      "firefox_android": "138"
    }
  },
  "javascript.builtins.Function.bind": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "6"
    }
  },
  "javascript.builtins.Function.name": {
    "support": {
      "chrome": "15",
      "chrome_android": "18",
      "edge": "14",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "6",
      "safari_ios": "6"
    }
  },
  "javascript.builtins.Intl.DateTimeFormat.DateTimeFormat": {
    "support": {
      "chrome": "24",
      "chrome_android": "25",
      "edge": "12",
      "firefox": "29",
      "firefox_android": "56",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.Iterator.Iterator": {
    "support": {
      "chrome": "122",
      "chrome_android": "122",
      "edge": "122",
      "firefox": "131",
      "firefox_android": "131",
      "safari": "18.4",
      "safari_ios": "18.4"
    }
  },
  "javascript.builtins.JSON": {
    "support": {
      "chrome": "3",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "3.5",
      "firefox_android": "4",
      "safari": "4",
      "safari_ios": "4"
    }
  },
  "javascript.builtins.Map": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "13",
      "firefox_android": "14",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Math.acosh": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.atanh": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.cbrt": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.clz32": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "31",
      "firefox_android": "31",
      "safari": "7",
      "safari_ios": "7"
    }
  },
  "javascript.builtins.Math.f16round": {
    "support": {
      "chrome": "135",
      "chrome_android": "135",
      "edge": "135",
      "firefox": "129",
      "firefox_android": "129",
      "safari": "18.2",
      "safari_ios": "18.2"
    }
  },
  "javascript.builtins.Math.fround": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "26",
      "firefox_android": "26",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.imul": {
    "support": {
      "chrome": "28",
      "chrome_android": "28",
      "edge": "12",
      "firefox": "20",
      "firefox_android": "20",
      "safari": "7",
      "safari_ios": "7"
    }
  },
  "javascript.builtins.Math.log10": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.log1p": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.log2": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Math.sign": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Math.trunc": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Number.MAX_SAFE_INTEGER": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "31",
      "firefox_android": "31",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.isFinite": {
    "support": {
      "chrome": "19",
      "chrome_android": "25",
      "edge": "12",
      "firefox": "16",
      "firefox_android": "16",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.isInteger": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "16",
      "firefox_android": "16",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.isNaN": {
    "support": {
      "chrome": "25",
      "chrome_android": "25",
      "edge": "12",
      "firefox": "15",
      "firefox_android": "15",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.isSafeInteger": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "32",
      "firefox_android": "32",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.parseFloat": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.parseInt": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "25",
      "firefox_android": "25",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Number.toExponential": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "2",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Object.assign": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "34",
      "firefox_android": "34",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Object.defineProperties": {
    "support": {
      "chrome": "5",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Object.defineProperty": {
    "support": {
      "chrome": "5",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "6"
    }
  },
  "javascript.builtins.Object.entries": {
    "support": {
      "chrome": "54",
      "chrome_android": "54",
      "edge": "14",
      "firefox": "47",
      "firefox_android": "47",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "javascript.builtins.Object.fromEntries": {
    "support": {
      "chrome": "73",
      "chrome_android": "73",
      "edge": "79",
      "firefox": "63",
      "firefox_android": "63",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "javascript.builtins.Object.getOwnPropertyDescriptor": {
    "support": {
      "chrome": "5",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Object.getOwnPropertyDescriptors": {
    "support": {
      "chrome": "54",
      "chrome_android": "54",
      "edge": "15",
      "firefox": "50",
      "firefox_android": "50",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.Object.getPrototypeOf": {
    "support": {
      "chrome": "5",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "3.5",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Object.groupBy": {
    "support": {
      "chrome": "117",
      "chrome_android": "117",
      "edge": "117",
      "firefox": "119",
      "firefox_android": "119",
      "safari": "17.4",
      "safari_ios": "17.4"
    }
  },
  "javascript.builtins.Object.hasOwn": {
    "support": {
      "chrome": "93",
      "chrome_android": "93",
      "edge": "93",
      "firefox": "92",
      "firefox_android": "92",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "javascript.builtins.Object.hasOwnProperty": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "3",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.Object.is": {
    "support": {
      "chrome": "19",
      "chrome_android": "25",
      "edge": "12",
      "firefox": "22",
      "firefox_android": "22",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Object.keys": {
    "support": {
      "chrome": "5",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.Object.setPrototypeOf": {
    "support": {
      "chrome": "34",
      "chrome_android": "34",
      "edge": "12",
      "firefox": "31",
      "firefox_android": "31",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Object.values": {
    "support": {
      "chrome": "54",
      "chrome_android": "54",
      "edge": "14",
      "firefox": "47",
      "firefox_android": "47",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "javascript.builtins.Promise": {
    "support": {
      "chrome": "32",
      "chrome_android": "32",
      "edge": "12",
      "firefox": "29",
      "firefox_android": "29",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.Promise.allSettled": {
    "support": {
      "chrome": "76",
      "chrome_android": "76",
      "edge": "79",
      "firefox": "71",
      "firefox_android": "79",
      "safari": "13",
      "safari_ios": "13"
    }
  },
  "javascript.builtins.Promise.any": {
    "support": {
      "chrome": "85",
      "chrome_android": "85",
      "edge": "85",
      "firefox": "79",
      "firefox_android": "79",
      "safari": "14",
      "safari_ios": "14"
    }
  },
  "javascript.builtins.Promise.finally": {
    "support": {
      "chrome": "63",
      "chrome_android": "63",
      "edge": "18",
      "firefox": "58",
      "firefox_android": "58",
      "safari": "11.1",
      "safari_ios": "11.3"
    }
  },
  "javascript.builtins.Promise.try": {
    "support": {
      "chrome": "128",
      "chrome_android": "128",
      "edge": "128",
      "firefox": "134",
      "firefox_android": "134",
      "safari": "18.2",
      "safari_ios": "18.2"
    }
  },
  "javascript.builtins.Promise.withResolvers": {
    "support": {
      "chrome": "119",
      "chrome_android": "119",
      "edge": "119",
      "firefox": "121",
      "firefox_android": "121",
      "safari": "17.4",
      "safari_ios": "17.4"
    }
  },
  "javascript.builtins.Reflect.getPrototypeOf": {
    "support": {
      "chrome": "49",
      "chrome_android": "49",
      "edge": "12",
      "firefox": "42",
      "firefox_android": "42",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.Reflect.ownKeys": {
    "support": {
      "chrome": "49",
      "chrome_android": "49",
      "edge": "12",
      "firefox": "42",
      "firefox_android": "42",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.RegExp.escape": {
    "support": {
      "chrome": "136",
      "chrome_android": "136",
      "edge": "136",
      "firefox": "134",
      "firefox_android": "134",
      "safari": "18.2",
      "safari_ios": "18.2"
    }
  },
  "javascript.builtins.RegExp.flags": {
    "support": {
      "chrome": "49",
      "chrome_android": "49",
      "edge": "79",
      "firefox": "37",
      "firefox_android": "37",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Set": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "13",
      "firefox_android": "14",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.String.at": {
    "support": {
      "chrome": "92",
      "chrome_android": "92",
      "edge": "92",
      "firefox": "90",
      "firefox_android": "90",
      "safari": "15.4",
      "safari_ios": "15.4"
    }
  },
  "javascript.builtins.String.endsWith": {
    "support": {
      "chrome": "41",
      "chrome_android": "36",
      "edge": "12",
      "firefox": "17",
      "firefox_android": "17",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.String.includes": {
    "support": {
      "chrome": "41",
      "chrome_android": "41",
      "edge": "12",
      "firefox": "40",
      "firefox_android": "40",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.String.lastIndexOf": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.String.matchAll": {
    "support": {
      "chrome": "73",
      "chrome_android": "73",
      "edge": "79",
      "firefox": "67",
      "firefox_android": "67",
      "safari": "13",
      "safari_ios": "13"
    }
  },
  "javascript.builtins.String.padEnd": {
    "support": {
      "chrome": "57",
      "chrome_android": "57",
      "edge": "15",
      "firefox": "48",
      "firefox_android": "48",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.String.padStart": {
    "support": {
      "chrome": "57",
      "chrome_android": "57",
      "edge": "15",
      "firefox": "48",
      "firefox_android": "48",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.String.raw": {
    "support": {
      "chrome": "41",
      "chrome_android": "41",
      "edge": "12",
      "firefox": "34",
      "firefox_android": "34",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.String.repeat": {
    "support": {
      "chrome": "41",
      "chrome_android": "36",
      "edge": "12",
      "firefox": "24",
      "firefox_android": "24",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.String.replaceAll": {
    "support": {
      "chrome": "85",
      "chrome_android": "85",
      "edge": "85",
      "firefox": "77",
      "firefox_android": "79",
      "safari": "13.1",
      "safari_ios": "13.4"
    }
  },
  "javascript.builtins.String.split": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.String.startsWith": {
    "support": {
      "chrome": "41",
      "chrome_android": "36",
      "edge": "12",
      "firefox": "17",
      "firefox_android": "17",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.String.substr": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.String.toLowerCase": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.String.toUpperCase": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.builtins.String.trim": {
    "support": {
      "chrome": "4",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "3.5",
      "firefox_android": "4",
      "safari": "5",
      "safari_ios": "5"
    }
  },
  "javascript.builtins.String.trimEnd": {
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "79",
      "firefox": "61",
      "firefox_android": "61",
      "safari": "12",
      "safari_ios": "12"
    }
  },
  "javascript.builtins.String.trimStart": {
    "support": {
      "chrome": "66",
      "chrome_android": "66",
      "edge": "79",
      "firefox": "61",
      "firefox_android": "61",
      "safari": "12",
      "safari_ios": "12"
    }
  },
  "javascript.builtins.Symbol": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "36",
      "firefox_android": "36",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.builtins.Symbol.description": {
    "support": {
      "chrome": "70",
      "chrome_android": "70",
      "edge": "79",
      "firefox": "63",
      "firefox_android": "63",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "javascript.builtins.Temporal": {
    "support": {
      "chrome": "144",
      "chrome_android": "144",
      "edge": "144",
      "firefox": "139",
      "firefox_android": "139"
    }
  },
  "javascript.builtins.TypedArray": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.TypedArray.buffer": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.TypedArray.byteLength": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.TypedArray.byteOffset": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.TypedArray.length": {
    "support": {
      "chrome": "7",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "4",
      "firefox_android": "4",
      "safari": "5.1",
      "safari_ios": "4.2"
    }
  },
  "javascript.builtins.TypedArray.slice": {
    "support": {
      "chrome": "45",
      "chrome_android": "45",
      "edge": "12",
      "firefox": "38",
      "firefox_android": "38",
      "safari": "10",
      "safari_ios": "10"
    }
  },
  "javascript.builtins.WeakMap": {
    "support": {
      "chrome": "36",
      "chrome_android": "36",
      "edge": "12",
      "firefox": "6",
      "firefox_android": "6",
      "safari": "8",
      "safari_ios": "8"
    }
  },
  "javascript.builtins.globalThis": {
    "support": {
      "chrome": "71",
      "chrome_android": "71",
      "edge": "79",
      "firefox": "65",
      "firefox_android": "65",
      "safari": "12.1",
      "safari_ios": "12.2"
    }
  },
  "javascript.builtins.parseInt": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.classes.extends": {
    "support": {
      "chrome": "42",
      "chrome_android": "42",
      "edge": "13",
      "firefox": "45",
      "firefox_android": "45",
      "safari": "9",
      "safari_ios": "9"
    }
  },
  "javascript.operators.await": {
    "support": {
      "chrome": "55",
      "chrome_android": "55",
      "edge": "14",
      "firefox": "52",
      "firefox_android": "52",
      "safari": "10.1",
      "safari_ios": "10.3"
    }
  },
  "javascript.operators.import_meta": {
    "support": {
      "chrome": "64",
      "chrome_android": "64",
      "edge": "79",
      "firefox": "62",
      "firefox_android": "62",
      "safari": "11.1",
      "safari_ios": "12"
    }
  },
  "javascript.operators.object_initializer.spread_properties": {
    "support": {
      "chrome": "60",
      "chrome_android": "60",
      "edge": "79",
      "firefox": "55",
      "firefox_android": "55",
      "safari": "11.1",
      "safari_ios": "11.3"
    }
  },
  "javascript.operators.optional_chaining": {
    "support": {
      "chrome": "80",
      "chrome_android": "80",
      "edge": "80",
      "firefox": "74",
      "firefox_android": "79",
      "safari": "13.1",
      "safari_ios": "13.4"
    }
  },
  "javascript.statements.for_in": {
    "support": {
      "chrome": "1",
      "chrome_android": "18",
      "edge": "12",
      "firefox": "1",
      "firefox_android": "4",
      "safari": "1",
      "safari_ios": "1"
    }
  },
  "javascript.statements.for_of": {
    "support": {
      "chrome": "38",
      "chrome_android": "38",
      "edge": "12",
      "firefox": "13",
      "firefox_android": "14",
      "safari": "7",
      "safari_ios": "7"
    }
  }
}
